name: FreeCloud 自动续费

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 10:00（UTC+8）
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 拉取代码
      uses: actions/checkout@v3

    - name: 🐍 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 📦 安装依赖
      run: |
        pip install --no-cache-dir -r requirements.txt

    - name: 🔐 登录获取 cookies
      env:
        FC_USERNAME: ${{ secrets.FC_USERNAME }}
        FC_PASSWORD: ${{ secrets.FC_PASSWORD }}
      run: |
        python freecloud_login.py

    - name: 🔁 执行续费操作
      env:
        FC_MACHINE_ID: ${{ secrets.FC_MACHINE_ID }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        python freecloud_renew.py
