name: 测试

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "0 0 */6 * *"  # 每6天运行一次

jobs:
  renew-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run renew script
        env:
          FC_USERNAME: ${{ secrets.FC_USERNAME }}
          FC_PASSWORD: ${{ secrets.FC_PASSWORD }}
          FC_PORT: ${{ secrets.FC_PORT }}
        run: |
          node renew.js > result.txt

      - name: Send failure email
        if: failure()
        uses: cinotify/github-action@main
        with:
          to: ${{ secrets.FC_EMAIL }}
          subject: "❌ Freecloud Renew Failed - $(date +'%Y-%m-%d')"
          body: "<em>任务失败，详见附件</em>"
          type: "text/html"
          attachment: "result.txt"

      - name: Send success email
        if: success()
        uses: cinotify/github-action@main
        with:
          to: ${{ secrets.FC_EMAIL }}
          subject: "✅ Freecloud Renew Result - $(date +'%Y-%m-%d')"
          body: "<em>任务执行成功</em>"
          type: "text/html"
          attachment: "result.txt"
