name: Auto Renew 

on:
  schedule:
    - cron: "0 0 */6 * *"  # 每 6 天执行一次

jobs:
  run-renew-script:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      # 4. 运行 Python 脚本
      - name: Run renew script
        env:
          FC_PROFILES: ${{ secrets.FC_PROFILE }}  # 密钥注入
        run: |
          python freecloud_renew.py > result.txt
        shell: bash

      # 5. 发送失败邮件通知
      - name: Send Failure Notification
        if: ${{ failure() }}
        uses: cinotify/github-action@main
        with:
          to: ${{ secrets.FC_EMAIL }}
          subject: "❌ Freecloud Renew Task Failed - $(date +'%Y-%m-%d')"
          body: "<em>Freecloud renew task FAILED!!!</br>See the attachment </em>"
          type: "text/html"
          attachment: "result.txt"

      # 6. 发送成功邮件通知
      - name: Send Success Notification
        if: ${{ success() }}
        uses: cinotify/github-action@main
        with:
          to: ${{ secrets.FC_EMAIL }}
          subject: "✅ Freecloud Renew Task Result - $(date +'%Y-%m-%d')"
          body: "<em>Freecloud renew task succeeded. See log attached.</em>"
          type: "text/html"
          attachment: "result.txt"

  # 保活任务（防止GitHub关闭Schedule）
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
