name: 测试

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: '0 0 */6 * *'  # 每 6 天运行一次

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Renew Script
        env:
          USERNAME: ${{ secrets.FC_USERNAME }}
          PASSWORD: ${{ secrets.FC_PASSWORD }}
          FC_MACHINE_ID: ${{ secrets.FC_MACHINE_ID }}
        run: |
          node renew.js > result.txt

      - name: Send Failure Email
        if: ${{ failure() }}
        uses: cinotify/github-action@main
        with:
          to: ${{ secrets.FC_EMAIL }}
          subject: "❌ Freecloud Renew Failed - $(date +'%Y-%m-%d')"
          body: "<em>任务失败，详见附件</em>"
          type: text/html
          attachment: result.txt

      - name: Send Success Email
        if: ${{ success() }}
        uses: cinotify/github-action@main
        with:
          to: ${{ secrets.FC_EMAIL }}
          subject: "✅ Freecloud Renew Success - $(date +'%Y-%m-%d')"
          body: "<em>任务成功，详见附件</em>"
          type: text/html
          attachment: result.txt
